---
title: "ALEXIS 106: Method"
author: "Mats E. Nilsson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This packages contains data from an experiment on auditory abilities in blind and sighted listeners. The experiment was called ALEXIS 106, and the data set is called `data106`. 

## Background and aim

Many blind individuals use information available in sound reflections to detect and localize objects, so called echolocation. Echolocation may involve self-generated vocalizations, e.g., click sounds, or sounds generated by external sources in the environment, such as the sound from a car passing by.  

Several studies have shown that blind listeners typically perform better than sighted listeners on echolocation tasks. This is presumably the results of many years of experience with navigating the environment without the aid of visual input. However, sighted listeners without any experience of echolocation can fairly quickly learn to perform well on specific echolocation tasks in laboratory settings.

The aim of this experiment was to compare blind and sighted listeners performance on four basic auditory tasks potentially related to human echolocation, to determine to what extent, of any, blind would perform better. The four abilities relates to changes in the acoustic signal as a direct sound is combined with its reflection from a nearby object. 

(1) The time-averaged sound pressure level (SPL) of the combined sound will be greater than the SPL of the direct sound. Thus, *intensity discrimination* is an ability that may be potentially useful for echolocation.  

(2) The direct and reflected sound will be correlated, resulting in a peak in the auto-correlation function at a position corresponding to the time-separation between direct and reflected sound. The amplitude of this peak relates to the relative amplitude of direct and reflected sound. Thus, the ability to detect weak indications of auto-correlation may potentially be useful for echolocation. This ability is here measured in what is called a *time-separation detection* task.

(3) As the distance between listener and reflecting object changes, the location of the peak in the auto-correlation function will change. Thus a change in the auto-correlation function may provide information on distance to the reflecting object and thus may be an aspect relevant for echolocation. This relates to the ability to discriminate differences in time-separation  between sounds combined of direct and reflected sound. This ability is here measured in what is called a *time-separation discrimination* task.

(4) The spectral composition of the combined sound may differ from the spectral composition of the direct sound. This is true in particular for small reflecting objects that will function as low-pass filters because sound wavelengths greater than the size of the object will be diffracted around the object. Thus, the ability to detect small relative increments in the high-frequency part of the spectrum may be useful for echolocation. This ability is here measured in what is called a *high-frequency detection* task. 

## Method

### Stimuli
The experiment included four experimental conditions, each containing one constant standard stimulus and one variable target stimulus, both 0.4 s long.  

(1) *Intensity discrimination*. The standard stimulus was a white noise. The variable stimulus was the same white noise with a variable sound pressure level (always higher than the standard). Perceptually, the difference between standard and variable was a difference in loudness. Threshold data for this condition are given in the variable `th.1`, unit decibel re standard.

(2) *Time-separation detection*. The standard stimulus was a white noise. The variable stimulus was composed of the standard noise and a copy of the standard noise added to itself with a time-delay of 2 ms. The level of the added copy varied from equal to the standard to a lower level, depending on the listener's performance. The overall level of the variable sound was always set equal to the standard sound to keep standard and variable equal in loudness. Perceptually, the difference between standard and variable was a difference in sound character. Threshold data for this condition are given in the variable `th.2`, unit decibel re standard.

(3) *Time-separation discrimination*. The standard stimulus was a white noise added to itself with a 2 ms delay (non-overlapping part of the stimulus not included). The variable stimulus was the same white noise added to itself with a variable time-separation. The overall level of the variable sound was always set equal to the standard sound to keep standard and variable equal in loudness. Perceptually, the difference between standard and variable was a difference in sound character. Threshold data for this condition are given in the variable `th.3`, unit samples (sampling frequency was 96 kHz, so 1 sample = 1/96000 s).

(4) *High-frequency detection*. The standard stimulus was a white noise. The variable stimulus was composed of the standard noise combined with a high-pass filtered white noise (cut-off frequency 4 kHz). The level of the added high-frequency noise varied from equal to the standard to a lower level, depending on the listener's performance. The overall level of the variable sound was always set equal to the standard sound to keep standard and variable equal in loudness. Perceptually, the difference between standard and variable was a difference in sound character. Threshold data for this condition are given in the variable `th.4`, unit decibel re standard.

### Staircase procedure
Thresholds were estimated using a three-interval, two-alternative forced choice task with an adaptive two-down, one-up rule that tracks the listener's 71 % discrimination threshold. On the first interval, the standard was always presented. The second and third interval contained the standard and the variable in random order. The listeners task was to decide whether the second or the third interval contained a sound that differed from the first interval. This method is sometimes called "two-alternative forced choice with reminder", where the first interval serves as the reminder. This method was used because it is hard to specify what perceptual characteristic that differs between standard and variable (with exception for the intensity discrimination task where the sound differ in loudness).

The staircase procedure started with an easily perceived difference between standard and variable. Two successive correct responses led to a reduction of the variable measure of 37 % (a step size of log 0.2 units) until the fourth reversal and by 11 % (0.05 log units) thereafter. An incorrect response led to an increase by the step size, or to the starting value if the rule implied an exceedance of this value. The starting values were: (1) 10 dB for the intensity discrimination task, (2) 0 dB for the time-separation detection task, (3) 8 ms for the time-separation discrimination task, and (4) 0 dB for the High-frequency detection task.


### Threshold estimates
Five runs were conducted for each of the six stimulus conditions in a random order unique to each listener. For each run, the threshold was estimated as the geometric mean at reversal points, after the fourth reversal. The geometric mean of the five runs for each condition was used as the estimate of the listener's threshold for that condition.

### Listeners
Three groups of listeners were tested: 26 blind listeners, 26 sighted listeners, age-matched to the blind listeners, and 40 young listeners. These groups are referred to as "blind", "matched" and "young" in the data set, variable `group`. Data on age, sex, and hearing status are available in the data set. For the blind listeners, there are also information on age at blindness onset, and self-reported use of echolocation
